# Site settings
title: Holy to Joa Website
email: canmi1002@naver.com

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: holyToJoa
permalink: /:year/:month/:day/:title/
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: holyToJoa
#duoshuo_url: "http://holyToJoa.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: holyToJoa
disqus_url: "http://holyTojoa.github.io"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
